# -*- coding: utf-8 -*-
"""while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/196OxVNAjFMnFlgC5MTpPcYTvN73SkOyD

Compulsory Task 3
Follow these steps:

● Create a new file called while.py.

● Write a program that always asks the user to enter a number.

● When the user enters -1, the program should stop requesting the user to
enter a number,

● The program must then calculate the average of the numbers entered,
excluding the -1.

● Make use of the while loop repetition structure to implement the
program.

● Compile, save, and run your file.
"""

# create a new file called while.py

# initialize variables
number = 0
count = 0
total = 0

# loop to get user input
while number != -1:
    number = int(input("Enter a number (the number shouldnt be -1): "))
    if number != -1:
        total += number
        count += 1
# calculate and print average
if count > 0:
    avg = total / count
    print("Average of numbers entered is:", avg)
else:
    print("No numbers entered")