# -*- coding: utf-8 -*-
"""replace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12AswujhZYeLbMkDMwnTjK6CIqC0VzYzw

Compulsory Task 2
Follow these steps:

● Create a new Python file in this folder called replace.py.

● Save the sentence: “The!quick!brown!fox!jumps!over!the!lazy!dog!.” as a
single string.

○ Reprint this sentence as “The quick brown fox jumps over the lazy
dog.” using the replace() function to replace every “!” exclamation
mark with a blank space.

○ Reprint that sentence as: “THE QUICK BROWN FOX JUMPS OVER
THE LAZY DOG.” using the upper() function

○ Print the sentence in reverse.
"""

sentence = 'The!quick!brown!fox!jumps!over!the!lazy!dog!.'
new_sentence = sentence.replace("!" , " ")
print(new_sentence)

print(new_sentence.upper())

print(new_sentence[::-1] )