# -*- coding: utf-8 -*-
"""strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ZqwCSYS-Ns3wdHXStPW_f0YMzP1kyP4

Compulsory Task 1

Follow these steps:

● Create a new Python file in this folder called strings.py

● Declare a variable called hero that contains the value “$$$Superman$$$”

● Use the string manipulation method strip() and print hero so the
output is: Superman
"""

hero = '$$$Superman$$$'
print(hero.strip('$'))