# -*- coding: utf-8 -*-
"""full_name.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GhhuzDMK9f4WnFjEcSVdvfub4gyWYeg_
"""

'''
Task 3
This program will be used to validate that a user inputs at least two names when
asked to enter their full name.
● Ask the user to input their full name.
● Perform some validation to check that the user has entered a full name.
Give an appropriate error message if they haven’t. One of the following
messages should be displayed based on the user’s input:
o “You haven’t entered anything. Please enter your full name.”
o “You have entered less than 4 characters. Please make sure that you
have entered your name and surname.”
o “You have entered more than 25 characters. Please make sure that
you have only entered your full name.”
o “Thank you for entering your name.”
The error message examples should help you to determine the sorts of
checks your program will need to perform on the data that the user
provides.
'''

#creating function for conditions
def validate(name):
    if len(name) == 0:
        return "You haven't entered anything. Please enter your full name."
    elif len(name) < 4:
        return "You have entered less than 4 characters. Please make sure that you have entered your name and surname."
    elif len(name) > 25:
        return "You have entered more than 25 characters. Please make sure that you have only entered your full name."
    elif " " not in name:
        return "Please make sure you have entered both your first name and surname."
    else:
        return None

# Ask user to input their full name
full_name = input("Please enter your full name: ")


# Validating name entered
error_message = validate(full_name)


# Print the error message if there is one
if error_message:
    print(error_message)
else:
    print("Thank you for entering your full name.")