# -*- coding: utf-8 -*-
"""hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KVZB3tI-MCNWGzuutoE1B4UsgR8bfTxu

Compulsory Task 1
Follow these steps:

● Create a new Python file in this folder called hello_world.py

● Inside this file, write Python code to take in a user’s name using input()
and then print out the name.

● Also, take in a user’s age using the same method and print out their age.

● Finally, print the string “Hello World!” on a new line
"""

user_name = input('PLEASE ENTER YOUR NAME:     ')
print('Name:' +'  ' + user_name)
user_age = input('PLEASE ENTER YOUR AGE:     ')
print('Age:' +'  ' + user_age)
print('Hello World!')