# -*- coding: utf-8 -*-
"""menu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yFGCFCSQ4DzshwzaKxUfzDIBRk9BNO0J

Compulsory Task 2
Follow these steps:

● Create a new Python file in this folder called menu.py

● Write a program that asks the user to order their 3 favourite food items on
a menu using input(). Store them as variables item1, item2 and item3.

● Print each item separately.

○ E.g. your program could print:
Order confirmation! You have ordered:

Chicken 

nuggets

Fish and chips

Spaghetti bolognaise
"""

print('order your 3 favourite food items')
item1 = input('enter 1st food item:     ')
item2 = input('enter 2nd food item:     ')
item3 = input('enter 3rd food item:     ')
print ('Order comfirmation!You have ordered:')
print(item1)
print(item2)
print(item3)