# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sfgj-Cme9q7-TD_hPGTwvwvHAhDX3r_7

# *Task*

Follow these steps:

● Create a new Python file in this folder called task3.py.

● Design a program that determines the award a person competing in a
triathlon will receive.

● Your program should read in the times (in minutes) for all three events of a
triathlon, namely swimming, cycling, and running, and then calculate and
display the total time taken to complete the triathlon.

● The award a participant receives is based on the total time taken to
complete the triathlon. The qualifying time for awards is 100 minutes.
Display the award that the participant will receive based on the following
criteria:

Total time Award

Within qualifying time. Provincial Colours

Within 5 minutes of qualifying time. Provincial Half Colours

Within 10 minutes of qualifying time. Provincial Scroll

More than 10 minutes of qualifying time. No award
"""

# Define the qualifying time for awards
qualification_time = 100

print('please make sure your inputs numbers are in minutes.Thank you ')

# event times
swim = int(input("Enter the event time for the swimming  (in minutes):           "))
cycle = int(input("Enter the event time for the cycling  (in minutes):            "))
run = int(input("Enter the event time for the running  (in minutes):              "))

#  total time for the triathlon
total_time = swim + cycle + run
print ('your swim + cycle + run event times = ' + str(total_time))

# Award classification
if total_time <= qualification_time:
    print("Provincial Colours")
elif total_time <= qualification_time + 5:
    print("Provincial Half Colours")
elif total_time <= qualification_time + 10:
    print("Provincial Scroll")
else:
    print("No award")